static mapping P_ADX = ([
	"anran-zhang.anran"		:		([
		"party" : 	"gm",
		"type"	:		"ADX3",
		"ap"		:		120,
		"hit"		:		3,
		"at"		:		70,
		"da"		:		70,
		"mp"		:		80,
		"super" :		30
	]),
	"anran-zhang.jishi"		:		([
		"party" : 	"gm",
		"type"	:		"ADX2",
		"ap"		:		80,
		"hit"		:		2,
		"at"		:		50,
		"da"		:		80,
		"mp"		:		60,
	]),
	"banruo-zhang.chaodu"		:		([
		"party" : 	"sl",
		"type"	:		"ADX2",
		"ap"		:		120,
		"hit"		:		2,
		"at"		:		70,
		"da"		:		60,
		"mp"		:		80,
		"super"	:		30,
	]),
	"chousui-zhang.chousui"		:		([
		"party" : 	"xx",
		"type"	:		"ADX3",
		"ap"		:		120,
		"hit"		:		3,
		"at"		:		60,
		"da"		:		70,
		"mp"		:		50,
	]),
	"chuanyun-tui.chuanyun"		:		([
		"party" : 	"kl",
		"type"	:		"ADX2",
		"ap"		:		240,
		"hit"		:		3,
		"at"		:		80,
		"da"		:		200,
		"mp"		:		350,
		"super" :   60,
	]),

	"cihang-bian.cibei"		:		([
		"party" : 	"tls",
		"type"	:		"ADX4",
		"ap"		:		240,
		"hit"		:		4,
		"at"		:		120,
		"da"		:		200,
		"mp"		:		350,
		"super" :   50,	
		"hurt"	:   40
	]),
	"cuixin-zhang.cuixin"		:		([
		"party" : 	"quest",
		"type"	:		"ADX1",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"dafumo-quan.fumo"		:		([
		"party" : 	"sl",
		"type"	:		"ADX1",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"dagou-bang.pi"		:		([
		"party" : 	"gb",
		"type"	:		"ADX1",
		"ap"		:		80,
		"hit"		:		1,
		"at"		:		70,
		"da"		:		200,
		"mp"		:		200,
		"hurt"	:   100
	]),
	"dagou-bang.shuangjue"		:		([
		"party" : 	"gb",
		"type"	:		"ADX4",
		"ap"		:		320,
		"hit"		:		5,
		"at"		:		70,
		"da"		:		120,
		"mp"		:		350,
		"super"	:		40
	]),
	"dagou-bang.wugou"		:		([
		"party" : 	"gb",
		"type"	:		"ADXX",
		"ap"		:		720,
		"hit"		:		6,
		"at"		:		150,
		"da"		:		250,
		"mp"		:		500,
		"hurt"  :		50,
		"super"	:		100,
		"kill"	:		25
	]),
	"dashou-yin.baoping"		:		([
		"party" : 	"dls",
		"type"	:		"ADX1",
		"ap"		:		40,
		"hit"		:		1,
		"at"		:		50,
		"da"		:		60,
		"mp"		:		80,
		"hurt"  :   50, 
	]),
	"douzhuan-xingyi.bishen"		:		([
		"party" : 	"mr",
		"type"	:		"ADX2",
		"ap"		:		240,
		"hit"		:		4,
		"at"		:		100,
		"da"		:		150,
		"mp"		:		250,
		"hurt"	:		100,
	]),
	"douzhuan-xingyi.xingyi"		:		([
		"party" : 	"mr",
		"type"	:		"ADX4",
		"ap"		:		200,
		"hit"		:		4,
		"at"		:		50,
		"da"		:		50,
		"mp"		:		50,
		"super" :   50
	]),
	"duanjia-jianfa.fenglei"		:		([
		"party" : 	"tls",
		"type"	:		"ADX4",
		"ap"		:		160,
		"hit"		:		4,
		"at"		:		50,
		"da"		:		80,
		"mp"		:		160,
		"super" :		30,
		"hurt"  :   30  
	]),
	"duoming-jinhua.huayu"		:		([
		"party" : 	"mj",
		"type"	:		"ADX1",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"fanliangyi-dao.huayue"		:		([
		"party" : 	"hs",
		"type"	:		"ADX3",
		"ap"		:		400,
		"hit"		:		3,
		"at"		:		120,
		"da"		:		200,
		"mp"		:		350,
		"super"	: 	60
	]),
	"fengmo-zhang.feizhang"		:		([
		"party" : 	"gb",
		"type"	:		"ADX1",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"furong-jinzhen.qianshou"		:		([
		"party" : 	"wd",
		"type"	:		"ADX1",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"hamagong.hama"		:		([
		"party" : 	"quest",
		"type"	:		"ADX2",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"hanbing-mianzhang.xixue":([
		"party" : 	"mj",
		"type":"ADX1",
		"ap":80,
		"hit":1,
		"at":80,
		"da":100,
		"mp":200,
		"super":70,
	]),
	"hanbing-shenzhang.xuejiao":([
		"party" : 	"ss",
		"type":"ADX4",
		"ap":160,
		"hit":4,
		"at":80,
		"da":80,
		"mp":150,
		"super":50,
	]),
	"hansha-sheying.xiangyin"		:		([
		"party" : 	"sld",
		"type"	:		"ADX1",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"huagu-mianzhang.bujue"		:		([
		"party" : 	"sld",
		"type"	:		"ADX4",
		"ap"		:		800,
		"hit"		:		16,
		"at"		:		150,
		"da"		:		200,
		"mp"		:		300,
		"delay" :		0.2,
		"super" :		30,
		"hurt"	:		30
	]),
	"huashan-jianfa.lianhuan"		:		([
		"party" : 	"hs",
		"type"	:		"ADX3",
		"ap"		:		120,
		"hit"		:		3,
		"at"		:		60,
		"da"		:		80,
		"mp"		:		60,
	]),
	"huashan-jianfa.luomu"		:		([
		"party" : 	"hs",
		"type"	:		"ADX3",
		"ap"		:		320,
		"hit"		:		5,
		"at"		:		80,
		"da"		:		100,
		"mp"		:		250,
		"super" :		50,
		"hurt"	:		30
	]),
	"huashan-jianfa.yunv"		:		([
		"party" : 	"hs",
		"type"	:		"ADXX",
		"ap"		:		640,
		"hit"		:		19,
		"at"		:		100,
		"da"		:		120,
		"mp"		:		300,
		"super"	:		40,
		"delay"	:		0.2
	]),
	"huifeng-bian.huixuan"		:		([
		"party" : 	"gb",
		"type"	:		"ADX1",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"huifeng-jian.liaoyuan"		:		([
		"party" : 	"em",
		"type"	:		"ADX4",
		"ap"		:		240,
		"hit"		:		4,
		"at"		:		70,
		"da"		:		300,
		"mp"		:		250,
		"super" :   30 
	]),
	"hujia-daofa.feidao"		:		([
		"party" : 	"quest",
		"type"	:		"ADX1",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"hujia-daofa.luandao"		:		([
		"party" : 	"quest",
		"type"	:		"ADX1",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"hujia-daofa.roudao"		:		([
		"party" : 	"quest",
		"type"	:		"ADX1",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"hunyuan-zhang.wuji"		:		([
		"party" : 	"hs",
		"type"	:		"ADX2",
		"ap"		:		160,
		"hit"		:		1,
		"at"		:		100,
		"da"		:		150,
		"mp"		:		300,
		"super"	:		60,
		"hurt"	:		40
	]),
	"huoyan-dao.ran"		:		([
		"party" : 	"dls",
		"type"	:		"ADX1",
		"ap"		:		120,
		"hit"		:		1,
		"at"		:		100,
		"da"		:		80,
		"mp"		:		500,
		"super" :		50,
		"hurt"	:		25,
	]),
	"jieshou-jiushi.foguang"		:		([
		"party" : 	"em",
		"type"	:		"ADX1",
		"ap"		:		80,
		"hit"		:		1,
		"at"		:		80,
		"da"		:		150,
		"mp"		:		250,
		"super" :   30,
		"hurt"  : 	40
	]),
	"jinshe-jianfa.kuangwu"		:		([
		"party" : 	"quest",
		"type"	:		"ADX4",
		"ap"		:		160,
		"hit"		:		4,
		"at"		:		80,
		"da"		:		70,
		"mp"		:		100,
		"super" : 	30,
		"delay" : 	0.1
	]),
	"jiuyin-baiguzhua.jiuyin"		:		([
		"party" : 	"quest",
		"type"	:		"ADX4",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"jiuyin-baiguzhua.sanjue"		:		([
		"party" : 	"quest",
		"type"	:		"ADX4",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"jiuyin-shenzhang.shenzhang"		:		([
		"party" : 	"quest",
		"type"	:		"ADX2",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"jiuyin-shenzhang.yinyang"		:		([
		"party" : 	"quest",
		"type"	:		"ADX2",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"jiuyin-shenzhua.sanjue"		:		([
		"party" : 	"quest",
		"type"	:		"ADX4",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"kongming-quan.kong":([
		"party" : 	"quest",
		"type":"ADX5",
		"ap"	:	120,
		"hit" : 10,
		"at"	:	50,
		"da"	:	50,
		"mp"	:	80,
		"delay": 0.5,
	]),
	"kunlun-zhang.diezhang"		:		([
		"party" : 	"kl",
		"type"	:		"X",
		"ap"		:		360,
		"hit"		:		2,
		"at"		:		150,
		"da"		:		250,
		"mp"		:		400,
		"dp"		:		75,
		"hurt"	: 	100
	]),
	"lanhua-shou.fuxue"		:		([
		"party" : 	"thd",
		"type"	:		"ADX1",
		"ap"		:		80,
		"hit"		:		1,
		"at"		:		50,
		"da"		:		60,
		"mp"		:		300,
	]),
	"lianhua-zhang.yehuo"		:		([
		"party" :   "gb",
		"type"	:		"ADX3",
		"ap"		:		120,
		"hit"		:		3,
		"at"		:		60,
		"da"		:		50,
		"mp"		:		80,
		"super" :   30
	]),
	"lietian-fu.lihun"		:		([
		"party" : 	"tz",
		"type"	:		"X",
		"ap"		:		200,
		"hit"		:		3,
		"at"		:		50,
		"da"		:		120,
		"mp"		:		250,
		"dp"		: 	40,
		"super"	:		50,
		"hurt"	:		25
	]),
	"lieyan-dao.shenghuo"		:		([
		"party" : 	"mj",
		"type"	:		"ADX1",
		"ap"		:		200,
		"hit"		:		1,
		"at"		:		200,
		"da"		:		250,
		"mp"		:		500,
		"hurt"	:		100
	]),
	"lingshe-bianfa.sandou"		:		([
		"party" : 	"sld",
		"type"	:		"ADX3",
		"ap"		:		200,
		"hit"		:		3,
		"at"		:		80,
		"da"		:		150,
		"mp"		:		200,
		"super" :		30
	]),

	"liuye-daofa.daozhang"		:		([
		"party" : 	"tz",
		"type"	:		"ADX1",
		"ap"		:		360,
		"hit"		:		3,
		"at"		:		100,
		"da"		:		150,
		"mp"		:		350,
		"super" :		60
	]),
	"longzhua-gong.canyun"		:		([
		"party" : 	"sl",
		"type"	:		"ADX2",
		"ap"		:		80,
		"hit"		:		2,
		"at"		:		50,
		"da"		:		60,
		"mp"		:		80,
		"hurt"	:		30,
	]),
	"longzhua-gong.lianhuan"		:		([
		"party" : 	"sl",
		"type"	:		"ADXX",
		"ap"		:		400,
		"hit"		:		8,
		"at"		:		90,
		"da"		:		80,
		"mp"		:		120,
		"super"	:		30,
	]),
	"luoying-zhang.kuangfeng"		:		([
		"party" : 	"thd",
		"type"	:		"ADXE",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"luoying-zhang.pikong"		:		([
		"party" : 	"thd",
		"type"	:		"ADX1",
		"ap"		:		40,
		"hit"		:		1,
		"at"		:		1,
		"da"		:		200,
		"mp"		:		500,		
	]),
	"mantian-huayu.liuxing"		:		([
		"party" : 	"kl",
		"type"	:		"ADXE",
		"ap"		:		1000,
		"hit"		:		50,
		"at"		:		200,
		"da"		:		300,
		"mp"		:		500,
		"delay"	:		0.1		
	]),
	"mantian-huayu.tianhua"		:		([
		"party" : 	"kl",
		"type"	:		"ADX2",
		"ap"		:		120,
		"hit"		:		1,
		"at"		:		150,
		"da"		:		100,
		"mp"		:		300,
		"hurt"	: 	50
	]),
	"meinu-quanfa.baimei"		:		([
		"party" : 	"gm",
		"type"	:		"ADX3",
		"ap"		:		240,
		"hit"		:		3,
		"at"		:		80,
		"da"		:		120,
		"mp"		:		250,
		"super" :		60
	]),
	"miaojia-jianfa.ci"		:		([
		"party" : 	"quest",
		"type"	:		"ADX1",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"miaojia-jianfa.duoming"		:		([
		"party" : 	"quest",
		"type"	:		"ADX1",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"murong-daofa.daoying"		:		([
		"party" : 	"mr",
		"type"	:		"ADX4",
		"ap"		:		320,
		"hit"		:		4,
		"at"		:		70,
		"da"		:		120,
		"mp"		:		300,
		"super" :		50,
		"hurt"  :		50,
	]),
	"murong-jianfa.lianhuan"		:		([
		"party" : 	"mr",
		"type"	:		"ADXX",
		"ap"		:		640,
		"hit"		:		14,
		"at"		:		120,
		"da"		:		150,
		"mp"		:		350,
		"super" :		50,
		"delay" :		0.1		 
	]),
	"ningxue-shenzhua.ningxue"		:		([
		"party" : 	"quest",
		"type"	:		"ADX1",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"pangen-fu.jingtian"		:		([
		"party" : 	"tls",
		"type"	:		"ADX3",
		"ap"		:		200,
		"hit"		:		3,
		"at"		:		40,
		"da"		:		150,
		"mp"		:		400,
		"hurt"  :		75,
		"super"	:   60
	]),
	"pixie-jian.jue"		:		([
		"party" : 	"quest",
		"type"	:		"ADX1",
		"ap"		:		120,
		"hit"		:		1,
		"at"		:		100,
		"da"		:		100,
		"mp"		:		250,
	]),
	"qianzhu-wandushou.qianzhu"		:		([
		"party" : 	"quest",
		"type"	:		"ADX4",
		"ap"		:		240,
		"hit"		:		4,
		"at"		:		150,
		"da"		:		80,
		"mp"		:		230,
	]),
	"qianzhu-wandushou.wandu"		:		([
		"party" : 	"quest",
		"type"	:		"DP",
		"ap"		:		120,
		"at"		:		200,
		"cond"		:	"qzhu_poison",
		"time"		:	120,
	]),
	"qishang-quan.duanhun"		:		([
		"party" : 	"mj",
		"type"	:		"ADX4",
		"ap"		:		240,
		"hit"		:		4,
		"at"		:		150,
		"da"		:		120,
		"mp"		:		250,
		"super" :		50,
		"hurt"	:		100
	]),
	"quanzhen-jianfa.qixing"		:		([
		"type"	:		"ADX1",
		"ap"		:		120,
		"hit"		:		1,
		"at"		:		100,
		"da"		:		150,
		"mp"		:		300,
	]),
	"quanzhen-jianfa.sanqing"		:		([
		"type"	:		"ADXX",
		"ap"		:		720,
		"hit"		:		9,
		"at"		:		150,
		"da"		:		200,
		"mp"		:		300,
		"super" :		30,
		"delay" :		0.1
	]),
	"ranmu-daofa.fenwo"		:		([
		"party" : 	"sl",
		"type"	:		"ADX1",
		"ap"		:		80,
		"hit"		:		1,
		"at"		:		70,
		"da"		:		100,
		"mp"		:		150,
		"hurt"  :   50
	]),
	"riyue-bian.riyue"		:		([
		"party" : 	"sl",
		"type"	:		"ADX3",
		"ap"		:		120,
		"hit"		:		2,
		"at"		:		100,
		"da"		:		200,
		"mp"		:		150,
	]),
	"ruying-suixingtui.ruying"		:		([
		"party" : 	"sl",
		"type"	:		"ADX5",
		"ap"		:		200,
		"hit"		:		5,
		"at"		:		80,
		"da"		:		60,
		"mp"		:		100,
		"super"	:		30,
	]),
	"shenghuo-lingfa.tisha"		:		([
		"party" : 	"mj",
		"type"	:		"ADX4",
		"ap"		:		160,
		"hit"		:		4,
		"at"		:		70,
		"da"		:		50,
		"mp"		:		120,
		"super"	:		50,
		"hurt"	:		30
	]),
	"shenghuo-lingfa.xinmo":([
		"party" : 	"mj",
		"type":"ADXX",
		"ap":720,
		"hit":16,
		"at":100,
		"da":250,
		"mp":300,
		"super":50,
		"delay":0.1,
	]),
	"shenlong-tuifa.zhuiming"		:		([
		"type"	:		"ADX4",
		"ap"		:		240,
		"hit"		:		4,
		"at"		:		100,
		"da"		:		200,
		"mp"		:		300,
		"super" :   70
	]),
	"shenlong-tuifa.zhuihun"		:		([
		"party" : 	"sld",
		"type"	:		"ADX1",
		"ap"		:		80,
		"hit"		:		1,
		"at"		:		80,
		"da"		:		100,
		"mp"		:		200,
		"super" :   50
	]),
	"songshan-jian.feiwu"		:		([
		"type"	:		"ADX4",
		"ap"		:		240,
		"hit"		:		4,
		"at"		:		80,
		"da"		:		200,
		"mp"		:		200,
		"super" :   30,
		"hurt"	: 	50
	]),
	"songshan-jian.leiting"		:		([
		"type"	:		"ADX1",
		"ap"		:		80,
		"hit"		:		1,
		"at"		:		80,
		"da"		:		150,
		"mp"		:		250,
		"super" :		70,
		"hurt"	:		50
	]),
	"songshan-jian.longfeng"		:		([
		"type"	:		"ADX5",
		"ap"		:		480,
		"hit"		:		4,
		"at"		:		150,
		"da"		:		250,
		"mp"		:		300,
		"super" :		50
	]),
	"songyang-bian.lian"		:		([
		"type"	:		"ADX3",
		"ap"		:		120,
		"hit"		:		3,
		"at"		:		70,
		"da"		:		50,
		"mp"		:		60,
	]),
	"songyang-bian.luan"		:		([
		"type"	:		"ADXX",
		"ap"		:		720,
		"hit"		:		9,
		"at"		:		150,
		"da"		:		250,
		"mp"		:		350,
		"super"	:		40,
		"hurt"	:		30,
		"delay"	: 	0.1
	]),
	"taiji-jian.lian"		:		([
		"type"	:		"ADXX",
		"ap"		:		240,
		"hit"		:		6,
		"at"		:		100,
		"da"		:		120,
		"mp"		:		250,
		"delay" :		0.2,
		"super"	:		30 
	]),
	"taiji-jian.sanhuan"		:		([
		"type"	:		"ADX3",
		"ap"		:		120,
		"hit"		:		3,
		"at"		:		50,
		"da"		:		70,
		"mp"		:		60,
	]),
	"taiji-quan.ji"		:		([
		"type"	:		"ADX1",
		"ap"		:		40,
		"hit"		:		1,
		"at"		:		50,
		"da"		:		70,
		"mp"		:		60,
		"hurt"  :		50
	]),
	"taiji-quan.luanhuan"		:		([
		"type"	:		"ADX3",
		"ap"		:		320,
		"hit"		:		3,
		"at"		:		80,
		"da"		:		150,
		"mp"		:		250,
		"super" : 	60,
		"hurt"	:		40
	]),
	"taizu-quan.chong"		:		([
		"type"	:		"ADX1",
		"ap"		:		40,
		"hit"		:		1,
		"at"		:		50,
		"da"		:		30,
		"mp"		:		30,
	]),
	"tangshi-jianfa.erguang"		:		([
		"type"	:		"ADX1",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"tanzhi-shentong.huayu":([
		"type":"ADX1",
		"ap":160,
		"hit"		:		1,
		"at"		:		100,
		"da"		:		200,
		"mp"		:		250,
		"super" : 	30,
		"hurt"	:		70
	]),
	"tenglong-bifa.hero"		:		([
		"party"	:		"sld",
		"type"	:		"ADX3",
		"ap"		:		480,
		"hit"		:		3,
		"at"		:		100,
		"da"		:		200,
		"mp"		:		400,
		"hurt"	:		100
	]),
	"tenglong-bifa.xiaolian"		:		([
		"party"	:		"sld",
		"type"	:		"ADXX",
		"ap"		:		160,
		"hit"		:		4,
		"at"		:		70,
		"da"		:		70,
		"mp"		:		100,
		"super"	:		50
	]),
	"tianshan-zhang.luanwu"		:		([
		"type"	:		"ADXX",
		"ap"		:		800,
		"hit"		:		20,
		"at"		:		150,
		"da"		:		200,
		"mp"		:		300,
		"super" :		50,
		"delay" : 	0.1
	]),
	"tianwang-zhua.lietian"		:		([
		"type"	:		"ADX4",
		"ap"		:		320,
		"hit"		:		4,
		"at"		:		30,
		"da"		:		180,
		"mp"		:		500,
		"super" :		70,
		"hurt"	:		50	
	]),
	"tiezhang-zhangfa.honglei"		:		([
		"party" : "tz",
		"type"	:		"ADX2",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"tiezhang-zhangfa.tianlei"		:		([		
		"party" : "tz",
		"type"	:		"ADX1",
		"ap"		:		160,
		"hit"		:		1,
		"at"		:		80,
		"da"		:		180,
		"mp"		:		350,
		"super" :		80
	]),
	"tiezhang-zhangfa.xuanfeng"		:		([
		"party" : "tz",
		"type"	:		"ADX2",
		"ap"		:		80,
		"hit"		:		2,
		"at"		:		50,
		"da"		:		80,
		"mp"		:		50,
		"super" :		30 
	]),
	"wuhu-duanmendao.duan"		:		([
		"party" : "quest",
		"type"	:		"ADX3",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"xiangfu-lun.wushuai"		:		([
		"party" : "dls",
		"type"	:		"ADX5",
		"ap"		:		200,
		"hit"		:		5,
		"at"		:		50,
		"da"		:		80,
		"mp"		:		120,
		"super"	:		50,
	]),
	"xianglong-zhang.kanglong"		:		([
		"party" : "gb",
		"type"	:		"ADX1",
		"ap"		:		40,
		"hit"		:		1,
		"at"		:		70,
		"da"		:		40,
		"mp"		:		70,
	]),
	"xianglong-zhang.paiyun"		:		([
		"party" : "gb",
		"type"	:		"ADX2",
		"ap"		:		200,
		"hit"		:		2,
		"at"		:		80,
		"da"		:		200,
		"mp"		:		500,
		"super"	:		70
	]),
	"xingyi-zhang.riyue"		:		([
		"party" :   "mr",
		"type"	:		"ADX2",
		"ap"		:		160,
		"hit"		:		4,
		"at"		:		70,
		"da"		:		80,
		"mp"		:		120,
		"super" :   30
	]),
	"xuanfeng-tui.fengwu"		:		([
		"type"	:		"ADX3",
		"ap"		:		120,
		"hit"		:		3,
		"at"		:		50,
		"da"		:		60,
		"mp"		:		80,
		"super" :		20
	]),
	"xuanfeng-tui.kuangfeng"		:		([
		"type"	:		"ADXX",
		"ap"		:		720,
		"hit"		:		18,
		"at"		:		150,
		"da"		:		150,
		"mp"		:		250,
		"super"	:		30,
		"hurt"	: 	40,
		"delay" :   0.1
	]),
	"xuantie-jianfa.haichao"		:		([
		"type"	:		"ADX3",
		"ap"		:		240,
		"hit"		:		3,
		"at"		:		60,
		"da"		:		150,
		"mp"		:		300,
		"super" :		50	
	]),
	"xuanxu-daofa.xuanmen"		:		([
		"type"	:		"ADX5",
		"ap"		:		480,
		"hit"		:		5,
		"at"		:		100,
		"da"		:		150,
		"mp"		:		300,
		"super" :		50,
		"hurt"	:		50,
		"kill"	:		15
	]),
	"xuanyin-jian.xuanyin"		:		([
		"type"	:		"ADX3",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"xuedao-jing.shendao"		:		([
		"type"	:		"ADX4",
		"ap"		:		160,
		"hit"		:		4,
		"at"		:		50,
		"da"		:		60,
		"mp"		:		200,
		"super" :   30  
	]),
	"xunlei-jian.qinjian"		:		([
		"type"	:		"ADX4",
		"ap"		:		160,
		"hit"		:		4,
		"at"		:		50,
		"da"		:		70,
		"mp"		:		60,
	]),
	"xunlei-jian.xunlei"		:		([
		"type"	:		"ADXX",
		"ap"		:		640,
		"hit"		:		16,
		"at"		:		120,
		"da"		:		150,
		"mp"		:		300,
		"kill"  :		10,
		"delay" : 	0.1
	]),
	"yanxing-daofa.feiyan"		:		([
		"type"	:		"ADX3",
		"ap"		:		120,
		"hit"		:		3,
		"at"		:		50,
		"da"		:		70,
		"mp"		:		60,
	]),
	"yingou-bifa.cao"		:		([
		"type"	:		"ADX5",
		"ap"		:		200,
		"hit"		:		5,
		"at"		:		50,
		"da"		:		80,
		"mp"		:		120,
		"super" :		20
	]),
	"yingou-bifa.kai"		:		([
		"type"	:		"ADX1",
		"ap"		:		40,
		"hit"		:		1,
		"at"		:		60,
		"da"		:		50,
		"mp"		:		50,
	]),
	"yinlong-bian.feilong"		:		([
		"type"	:		"ADX3",
		"ap"		:		10,
		"hit"		:		9,
		"at"		:		999,
		"da"		:		7,
		"mp"		:		6,
	]),
	"yinsuo-jinling.sanwu":([
		"party" :		"gm",
		"type"	:		"ADX3",
		"ap"		:		480,
		"hit"		:		3,
		"at"		:		150,
		"da"		:		250,
		"mp"		:		350,
		"super" :		60,
		"hurt"	:		100
	]),
	"yiyang-zhi.ciqu"		:		([
		"party" : 	"tls",
		"type"	:		"ADX4",
		"ap"		:		0,
		"hit"		:		6,
		"at"		:		40,
		"da"		:		120,
		"mp"		:		250,
		"hurt"  :		60,
		"super" :		90
	]),
	"yiyang-zhi.sandie"		:		([
		"party" : 	"tls",
		"type"	:		"X",
		"ap"		:		0,
		"hit"		:		1,
		"at"		:		60,
		"da"		:		100,
		"mp"		:		150,
		"hurt"  :   75,
		"dp"		:		50,
		"d_ev"	:		100,
		"d_pa"  :		100,
		"time"  :		60
	]),
	"yiyang-zhi.sanmai"		:		([
		"party" : 	"tls",
		"type"	:		"ADX3",
		"ap"		:		120,
		"hit"		:		3,
		"at"		:		60,
		"da"		:		70,
		"mp"		:		70,
		"hurt"  :		25   
	]),
	"yuxiao-jian.feiying"		:		([
		"party" : 	"thd",
		"type"	:		"ADX5",
		"ap"		:		320,
		"hit"		:		5,
		"at"		:		100,
		"da"		:		150,
		"mp"		:		200,
		"super" :		30,
	]),
	"yuxiao-jian.qimen"		:		([
		"party" : 	"thd",
		"type"	:		"X",
		"ap"		:		480,
		"hit"		:		5,
		"at"		:		120,
		"da"		:		100,
		"mp"		:		300,
		"super" :   40,
		"d_at"	:   200,
		"d_ev"	:		200,
		"d_pa"	:		200,
		"time"	: 	60
	]),
	"yuxiao-jian.yuxiao"		:		([
		"party" : 	"thd",
		"type"	:		"ADX1",
		"ap"		:		80,
		"hit"		:		1,
		"at"		:		30,
		"da"		:		200,
		"mp"		:		300,
		"hurt"	:		30 
	]),
	"zhenshan-mianzhang.bingdi"		:		([
		"type"	:		"ADX2",
		"ap"		:		200,
		"hit"		:		3,
		"at"		:		70,
		"da"		:		120,
		"mp"		:		250,
		"hurt"	:		50
	]),
	"zhuihun-gou.jumie"		:		([
		"type"	:		"ADX4",
		"ap"		:		480,
		"hit"		:		4,
		"at"		:		120,
		"da"		:		200,
		"mp"		:		300,
		"super"	:		50,
		"hurt"	:		70,
		"delay" :   0.1
	]),
	"zui-gun.baxian"		:		([
		"party" : 	"sl",
		"type"	:		"ADX8",
		"ap"		:		160,
		"hit"		:		8,
		"at"		:		50,
		"da"		:		40,
		"mp"		:		50,
		"hurt"  :   50 
	]),
]);

static mapping P_AE = ([
	"canhe-zhi.guiyuan":		([
		"party" : 	"mr",
		"type"	:		"AE",
		"ap"		:		600,
		"at"		:		120,
	]),
	"chousui-zhang.fushidu":		([
		"party" : 	"xx",
		"type"	:		"AE",
		"ap"		:		320,
		"at"		:		70,
	]),
	"chuanyun-tui.feixing"		:		([
		"party" : 	"kl",
		"type"	:		"AE",
		"ap"		:		400,
		"at"		:		80,
	]),
	"huoyan-dao.fen":		([
		"party" : 	"dls",
		"type"	:		"AE",
		"ap"		:		600,
		"at"		:		100,
	]),
	"huashan-jianfa.wushuang":([
		"party" : 	"hs",
		"type":"AE",
		"ap":480,
		"at":80,
	]),
	"liuhe-daofa.sancai"		:		([
		"party" : 	"gb",
		"type"	:		"AE",
		"ap"		:		400,
		"at"		:		50,
	]),
	"taiji-jian.tongshou":		([
		"party" : 	"wd",
		"type"	:		"AE",
		"ap"		:		240,
		"at"		:		80,
	]),
	"tenglong-bifa.feiyan":		([
		"party" : 	"sld",
		"type"	:		"AE",
		"ap"		:		320,
		"at"		:		80,
	]),
	"tiezhang-zhangfa.tiezhang":		([
		"party" : 	"tj",
		"type"	:		"AE",
		"ap"		:		400,
		"at"		:		50,
	]),
	"weituo-chu.chaodu":		([
		"party" : 	"sl",
		"type"	:		"AE",
		"ap"		:		320,
		"at"		:		30,
	]),
]);


static mapping P_AP = ([
	"banruo-zhang.yipai"		:		([
		"party" : "sl",
		"type"	:		"AP",
		"ap":80,
		"at":50,
		"dp":25
	]),
	"dashou-yin.genben":([
		"party" : "dls",
		"type":"AP",
		"ap":120,
		"at":75,
		"dp":25
	]),
	"hanbing-shenzhang.junji":([
		"party" : "ss",
		"type":"AP",
		"ap":200,
		"at":50,
		"dp":70,
	]),
	"huashan-jianfa.cangsong":([
		"party" : "hs",
		"type":"AP",
		"ap":80,
		"at":50,
		"dp":25
	]),

	"lianhua-zhang.bingdi"		:		([
		"party" : 	"gb",
		"type"	:		"AP",
		"ap"		:		160,
		"at"		:		80,
		"dp"		:		40,
	]),
	"qingyan-zhang.piaoying":([
		"party" : "tls",
		"type":"AP",
		"ap":80,
		"at":50,
		"dp":25
	]),	
	"ranmu-daofa.fentian":([
		"party" : "sl",
		"type":"AP",
		"ap":200,
		"at":75,
		"dp":50
	]),
	"shenghuo-lingfa.yinfeng":([
		"party" : "mj",
		"type":"AP",
		"ap":120,
		"at":50,
		"dp":40
	]),
	"sixiang-zhang.shengxi"		:		([
		"party" : "em",
		"type"	:		"AP",
		"ap"		:		160,
		"at"		:		75,
		"dp"		:		50
	]),
	"taiji-quan.an":([
		"party" : "wd",
		"type":"AP",
		"ap":120,
		"at":75,
		"dp":25
	]),
	"tanzhi-shentong.shentong":([
		"party" : "thd",
		"type":"AP",
		"ap":240,
		"at":100,
		"dp":50
	]),
	"tenglong-bifa.guifei"		:		([
		"party"	:		"sld",
		"type"	:		"AP",
		"ap"		:		120,
		"at"		:		60,
		"dp"		:		35,
	]),
	"tianluo-diwang.qingyan":([
		"party" : "gm",
		"type":"AP",
		"ap":320,
		"at":90,
		"dp":80
	]),
	"tianshan-zhang.feizhi"		:		([
		"party" : 	"xx",
		"type"	:		"AP",
		"ap"		:		120,
		"at"		:		50,
		"dp"		:		50,
	]),
	"yingou-bifa.shigu":([
		"party" : "tz",
		"type":"AP",
		"ap":160,
		"at":75,
		"dp":50
	]),
	"tiezhang-zhangfa.heyi":([
		"party" : "tz",
		"type":"AP",
		"ap":160,
		"at":100,
		"dp":25
	]),
]);

static mapping P_BUF = ([
	"yijin-jing.jingang"		:		([
		"party" : "sl",
		"type":"BP",
		"ap"	: 	40,
		"pa"	:		60,
	]),
	"yijin-jing.buhuai"		:		([
		"party" : "sl",
		"type":"BD",
		"ap"		: 	80,
		"armor"	:		50,
	]),
	"anying-fuxiang.huashen":([
		"type":"BD",
		"ap":80,
		"ev":50,
	]),
	"zhuihun-gou.luan"		:		([
		"party" : "xx",
		"type":"BA",
		"ap"		:		200,
		"at"		:		60,
		"da"		:		40,
		"mp"		:		100,	
		"auto" 	:		1
	]),
	"chongling-jian.hebi":([
		"type":"BA",
		"ap":10,
		"at":999,
		"da":8,
		"mp":7,
		"ev":6,
		"pa":5,
	]),
	"fanliangyi-dao.hebi":([
		"type":"BA",
		"ap":10,
		"at":999,
		"da":8,
		"mp":7,
		"ev":6,
		"pa":5,
	]),
	"hamagong.nizhuan":([
		"type":"BA",
		"ap":10,
		"at":999,
		"da":8,
		"mp":7,
		"ev":6,
		"pa":5,
	]),
	"huashan-jianfa.junzi":([
		"party" : 	"hs",
		"type":"BD",
		"ap":80,
		"da":50,
	]),
	"huashan-jianfa.kuaijian"		:		([
		"party" : 	"hs",
		"type"	:		"BX",
		"ap"		:		800,
		"at"		:		150,
		"da"		:		300,
		"mp"		:		300,
		"super"	: 	50,
		"hurt"	:		50,
		"time"	:   18,
		"auto"	:		6
	]),
	"huashan-jianfa.shunv":([
		"party" : 	"hs",
		"type":"BA",
		"ap":80,
		"at":60,

	]),
	"huashan-jianfa.xiyi":([
		"party" : 	"hs",
		"type":"BP",
		"ap":80,
		"pa":70,

	]),
	"huifeng-jian.jue":([
		"type":"BA",
		"ap":80,
		"at":50,
		"mp":100,

	]),
	"jiuyin-shenfa.huanyinbu":([
		"type":"BD",
		"ap":10,
		"at":999,
		"da":8,
		"mp":7,
		"ev":6,
		"pa":5,
	]),

	"liangyi-jian.ding":([
		"type":"BD",
		"ap":160,
		"at":50,
		"da":50,
		"mp":100,
	]),
	"lingbo-weibu.luoshen":([
		"type":"BD",
		"ap":10,
		"at":999,
		"da":8,
		"mp":7,
		"ev":6,
		"pa":5,
	]),
	"ranmu-daofa.fenxin":([
		"type":"BA",
		"ap":320,
		"at":100,
		"da":100,
		"mp":250,
	]),
	"riyue-bian.fumoquan":([
		"type":"BS",
		"ap":240,
		"at":80,
		"da":50,
		"mp":80,
		"ev":60,
		"pa":60,

	]),
	"shuishangpiao.piao":([
		"type":"BD",
		"ap":80,
		"ev":70,
	]),
	"suibo-zhuliu.wuzhuan":([
		"type":"BD",
		"ap":40,
		"ev":40,
	]),
	"tanzhi-shentong.xinghe":([
		"type":"BA",
		"ap":200,
		"at":80,
		"mp":100,
		"auto":1
	]),
	"taiji-jian.raozhi"		:		([
		"type"	:		"BA",
		"ap"		:		640,
		"at"		:		150,
		"da"		:		200,
		"mp"		:		300,
		"ev"   	:		150,
		"pa"		:		150,
		"super"	:		50,
		"hurt"	: 	30,
		"auto" :		1,
		"time"	:		60 
	]),
	"tiezhang-zhangfa.zhangdao"		:		([
		"party" : "tz",
		"type"	:		"B",
		"ap"		:		640,
		"at"		:		180,
		"da"		:		150,
		"mp"		:		400,
		"super" :		50,
		"auto"  :   1,
		"hurt"  :		75,
		"pa"		:		200,
		"time"	:		60	
	]),
	"tiyunzong.zong":([
		"type":"BD",
		"ap":40,
		"ev":50,
	]),
	"xiangfu-lun.dazhuan":([
		"party"	:	"dls",
		"type"	:	"BS",
		"ap"		:	640,
		"at"		:	200,
		"da"		:	300,
		"mp"		:	500,
		"pa"		:	150,
		"armor"	:	600,
		"super" : 50,
		"auto"  : 2
	]),
	"xianglong-zhang.xiao":([
		"party"	:	"gb",
		"type":"BA",
		"ap":200,
		"at":0,
		"da":70,
		"mp":150,
	]),
	"xuantie-jianfa.wujian":([
		"type":"BA",
		"ap":320,
		"at":100,
		"da":100,
		"mp":250,
		"ev":80,
		"pa":80,
	]),
	"xuedao-jing.jixue":([
		"type":"BA",
		"ap":10,
		"at":999,
		"da":8,
		"mp":7,
		"ev":6,
		"pa":5,
	]),
	"yanxing-daofa.chuanliu":([
		"type":"BA",
		"ap":240,
		"at":80,
		"da":80,
		"mp":200,
	]),
	"yanxing-daofa.huanying"		:		([
		"type"	:		"BA",
		"ap"		:		800,
		"at"		:		200,
		"da"		:		150,
		"mp"		:		450,
		"super" :		100,
		"hurt"  :   100,
		"ev"    :		200,
		"auto"  :   3
	]),
	"yiyang-zhi.liumai":([
		"type"	:	"BA",
		"ap"		:	120,
		"at"		:	50,
		"mp"		:	80,
		"auto"	: 1
	]),
	"jingang-quan.fumo":([
		"type":"BA",
		"ap":80,
		"at":40,
		"da":10,
		"mp":60,
	]),
	"poyu-quan.leidong":([
		"type":"BX",
		"ap":200,
		"at":70,
		"da":30,
		"mp":100,
		"kill":10,
		"auto":1,
	]),
	"weituo-chu.leidong":([
		"type":"BA",
		"ap":160,
		"at":40,
		"mp":140,
		"kill":10,
	]),
	"yunu-jianfa.suxin":([
		"type":"BA",
		"ap":120,
		"at":50,
		"ev":50,
		"pa":50,
		"auto" : 0.5
	]),
]);

static mapping P_DE = ([
	"dagou-bang.ban":([
		"type":"DD",
		"ap":200,
		"at":100,
		"d_ev":100,
		"d_pa":100,
		"time":120,
		"cond":"",
	]),
	"dagou-bang.chan":([
		"type":"DB",
		"ap":120,
		"at":80,
		"time":30
	]),
	"dagou-bang.chuo":([
		"type":"DF",
		"ap":120,
		"at":100,
		"time":60,
		"cond":"no_force",
	]),
	"dagou-bang.tiao":([
		"type":"DW",
		"ap":80,
		"at":50,
	]),
	"dagou-bang.yin":([
		"type":"DS",
		"ap":120,
		"at":70,
		"time":60,
		"cond":"no_perform",
	]),
	"dagou-bang.zhuan":([
		"type":"DB",
		"ap":10,
		"at":999,
		"d_at":9,
		"d_da":8,
		"d_mp":7,
		"d_ev":6,
		"d_pa":5,
		"time":60,
		"cond":"",
	]),
	"dashou-yin.neifu":([
		"type":"DF",
		"ap":120,
		"at":80,
		"time":60,
		"cond":"no_exert",
	]),
	"dashou-yin.waifu":([
		"type":"DS",
		"ap":80,
		"at":60,
		"time":60,
		"cond":"no_perform",
	]),
	"dugu-jiujian.kuangfeng":([
		"type":"DW",
		"ap":120,
		"at":80,
	]),
	"dugu-jiujian.zongjue":([
		"type":"DS",
		"ap":160,
		"at":100,
		"time":30,
		"cond":"no_enable",
	]),
	"huashan-jianfa.yangwu":([
		"type":"DB",
		"ap":40,
		"at":50,
		"time" : 5,
		"cond":"",
	]),
	"liangyi-jian.kunlong":([
		"party":"kl",
		"type":"DA",
		"ap":200,
		"at":80,
		"d_at":50,
		"d_dex"	:	10,
		"d_ev" 	: 100,
		"d_pa" 	: 100,
		"time"  : 60
	]),
	"lingshe-bianfa.chan":([
		"party":"sld",
		"type":"DB",
		"ap":200,
		"at":100,
		"d_at":200,
		"time":60,
		"cond":"",
	]),
	"meinu-quanfa.shexin":([
		"type":"DA",
		"ap":120,
		"at":80,
		"d_at":50,
		"d_da":50,
		"d_mp":100,
		"time":60,
		"cond":"",
	]),
	"murong-jianfa.sanhua":([
		"type":"X",
		"ap":120,
		"at":70,
		"hit" :3,
		"da":70,
		"mp":50,
		"dp":35,  
		"d_mp":100,
		"d_at":50,
		"d_da":70,
		"time":60,
		"cond":"",
	]),
	"pixie-jian.cimu":([
		"type":"DA",
		"ap":160,
		"at":150,
		"d_at":100,
		"d_ev":50,
		"d_pa":50,
		"time":60,
		"cond":"",
	]),
	"qiankun-danuoyi.hua":([
		"type":"DA",
		"ap":10,
		"at":999,
		"d_at":9,
		"d_da":8,
		"d_mp":7,
		"d_ev":6,
		"d_pa":5,
		"time":8,
		"cond":"",
	]),
	"qiankun-danuoyi.xu":([
		"type":"DA",
		"ap":10,
		"at":999,
		"d_at":9,
		"d_da":8,
		"d_mp":7,
		"d_ev":6,
		"d_pa":5,
		"time":8,
		"cond":"",
	]),
	"qiankun-danuoyi.yi":([
		"type":"DA",
		"ap":10,
		"at":999,
		"d_at":9,
		"d_da":8,
		"d_mp":7,
		"d_ev":6,
		"d_pa":5,
		"time":8,
		"cond":"",
	]),
	"qiankun-danuoyi.yin":([
		"type":"DA",
		"ap":10,
		"at":999,
		"d_at":9,
		"d_da":8,
		"d_mp":7,
		"d_ev":6,
		"d_pa":5,
		"time":8,
		"cond":"",
	]),
	"shenghuo-lingfa.duo":([
		"type":"DW",
		"ap":120,
		"at":80,
	]),
	"shenghuo-lingfa.ji":([
		"type":"DS",
		"ap":80,
		"d_at":30,
		"d_ev":30,
		"d_pa":30,
		"time":60,
	]),
	"taiji-jian.chan":([
		"type":"DB",
		"ap":10,
		"at":999,
		"d_at":9,
		"d_da":8,
		"d_mp":7,
		"d_ev":6,
		"d_pa":5,
		"time":8,
		"cond":"",
	]),
	"tanzhi-shentong.qiankun":([
		"type":"DH",
		"ap":400,
		"at":150,
		"time":120
	]),
	"tanzhi-shentong.tan":([
		"type":"DB",
		"ap":80,
		"at":80,
		"time":5,
	]),
	"tiezhang-zhangfa.heisha":([
		"type":"DF",
		"ap":200,
		"at":80,
		"d_at":50,
		"d_da":80,
		"d_mp":200,
		"time":60,
		"cond":"no_exert",
	]),
	"tiezhang-zhangfa.pangen":([
		"type":"DB",
		"ap":80,
		"at":70,
		"time":5,
	]),
	"tiezhang-zhangfa.qinna":([
		"type":"DW",
		"ap":80,
		"at":80,
	]),
	"wuxiang-zhi.qiankun":([
		"type":"DB",
		"ap":160,
		"at":80,
		"time":30,
		"cond":"busy",
	]),
	"xuanyin-jian.zhan":([
		"type":"DA",
		"ap":10,
		"at":999,
		"d_at":9,
		"d_da":8,
		"d_mp":7,
		"d_ev":6,
		"d_pa":5,
		"time":8,
		"cond":"",
	]),
	"yinlong-bian.chanrao":([
		"type":"DB",
		"ap":10,
		"at":999,
		"d_at":9,
		"d_da":8,
		"d_mp":7,
		"d_ev":6,
		"d_pa":5,
		"time":8,
		"cond":"",
	]),
	"yinsuo-jinling.yueyin":([
		
		"type":"DB",
		"ap":200,
		"at":100,
		"d_ev":150,
		"d_pa":150,
		"time":60,
		"cond":"no_perform",
	]),
	"yizhi-chan.wofo":([
		"party" : "sl",
		"type":"DC",
		"ap":320,
		"at":200,
		"time":60,
		"cond":"no_perform",
	]),
	"canhe-zhi.ci":([
		"type":"DA",
		"ap":120,
		"at":70,
		"d_ev":80,
		"d_pa":80,
		"time":60,
		"cond":"no_perform",
	]),
	"chousui-zhang.biyan":([
		"party" : "xx",
		"type":"DP",
		"ap":120,
		"at":100,
		"time":60,
		"cond":"xx_ruanjing"
	]),
	"chousui-zhang.yinhuo":([
		"party" : "xx",
		"type":"DP",
		"ap":80,
		"at":50,
		"time":60,
		"cond":"xx_poison"
	]),
	"chousui-zhang.huoqiu":([
		"type":"DE",
		"ap":240,
		"at":80,
	]),
	"dugu-jiujian.po":([
		"type":"DC",
		"ap":80,
		"at":100,
		"d_at":100,
		"d_da":50,
		"time":60,
		"cond":"no_perform",
	]),
	"huifeng-jian.mie":([
		"type":"DA",
		"ap":120,
		"at":80,
		"d_at":50,
		"d_ev":50,
		"d_pa":50,
		"time":30,
	]),
	"huifeng-jian.miejue":([
		"type":"X",
		"ap":400,
		"at":120,
		"da":80,
		"mp":200,
		"d_at":100,
		"d_ev":100,
		"d_pa":100,
		"time":60,
		"cond":"no_perform",
	]),	
	"kongming-quan.ming":([
		"type":"DA",
		"ap"		:	40,
		"d_da"	:	50,
		"time" 	: 60,
	]),
	"lianhua-zhang.cailian":([
		"party" : "gb",
		"type":"DS",
		"ap":160,
		"at":80,
		"d_at":30,
		"d_da":70,
		"d_mp":100,
		"time":60,
		"cond":"",
	]),
	"nianhua-zhi.fuxue":([
		"party" : "sl",
		"type":"DB",
		"ap":120,
		"at":120,
		"time":120,
		"cond":"fx_busy",
	]),
	"qianye-shou.qianshou":([
		"type":"DA",
		"ap":160,
		"at":60,
		"d_at":50,
		"d_ev":70,
		"d_pa":70,
		"time":30,
		"cond":"",
	]),
	"sanhua-zhang.sanhua":([
		"party" : "sl",
		"type":"ADX1",
		"hit" : 1,
		"ap":120,
		"at":80,
		"da":120,
		"mp":250,
		"hurt":30,
		"super":50,
	]),
	"sanyin-zhua.duzhi":([
		"type":"DN",
		"ap":10,
		"at":999,
		"d_at":9,
		"d_da":8,
		"d_mp":7,
		"d_ev":6,
		"d_pa":5,
		"time":8,
		"cond":"",
	]),
	"songyang-shou.yinyang":([
		"type":"DA",
		"ap":200,
		"at":150,
		"d_at":100,
		"d_da":70,
		"time":120,
		"cond":"cold_poison",
	]),
	"taiji-quan.zhannian"		:		([
		"type"	:		"DA",
		"ap"		:		200,
		"at"		: 	80,
		"d_at":80,
		"d_da":80,
		"d_mp":200,
		"time":60,
	]),
	"yizhi-chan.qiankun":([
		"party" : "sl",
		"type":"DB",
		"ap":10,
		"at":999,
		"d_at":9,
		"d_da":8,
		"d_mp":7,
		"d_ev":6,
		"d_pa":5,
		"time":8,
		"cond":"",
	]),
	"yuxiao-jian.cuiyin":([
		"type":"DB",
		"ap":200,
		"at":80,
	]),
	"sanyin-zhua.duzhi":([
		"party" : "xx",
		"type":"AP",
		"ap":160,
		"at":80,
		"time":60,
		"cond":"xx_huagong"  
	]),
	"hanbing-shenzhang.hanbing":([
		"party" : "ss",
		"type":"DP",
		"ap":120,
		"at":80,
		"d_ev":100,
		"d_da":100,
		"time":60,
		"cond":"",
	]),
	"qishang-quan.qishang":([
		"type":"DG",
		"ap":400,
		"at":150,
		"d_int":20,
		"d_str":20,
		"d_con":20,
		"d_dex":20,
		"time":60,
		"cond":"no_perform",
	]),
	"longxiang-boruo.fanchang":([
		"party" : "dls",
		"type":"DS",
		"ap":160,
		"d_at":30,
		"d_ev":50,
		"d_pa":50,
		"time":60,
	]),
	"longxiang-boruo.shield":([
		"party" : "dls",
		"type":"BD",
		"ap":80,
		"pa":40,
		"armor":30,
	]),
	"longxiang-boruo.longxiang":([
		"party" : "dls",
		"type":"BD",
		"ap":80,
		"da":30,
		"at":30,
	]),
	"guiyuan-tunafa.guiyuan":([
		"party" : "tz",
		"type":"BA",
		"ap":40,
		"mp":30,
		"at":30,
	]),
	"hanbing-zhenqi.hanbing":([
		"party" : "ss",
		"type":"BA",
		"ap":40,
		"at":30,
	]),
	"hanbing-zhenqi.huti":([
		"party" : "ss",
		"type":"BP",
		"ap":40,
		"pa":40,
	]),
	"hanbing-zhenqi.juhan":([
		"party" : "ss",
		"type":"BD",
		"ap":40,
		"mp":70,
	]),
	"hanbing-zhenqi.liaodu":([
		"party" : "ss",
		"type":"B",
		"ap":40,
	]),
	"shenyuan-gong.shenyuan":([
		"party" : "mr",
		"type":"BS",
		"ap":120,
		"at": 40,
		"pa": 50  
	]),
	"huntian-qigong.powerup":([
		"party" : "gb",
		"type":"BD",
		"ap":120,
		"da": 80,
	]),
	"huntian-qigong.shentong":([
		"party" : "gb",
		"type":"BF",
		"ap": 40,
	]),
	"huntian-qigong.huntian":([
		"party" : "gb",
		"type":"BP",
		"ap":	40,
		"armor": 40,
	]),
	"yunu-xinjing.xinjing":([
		"party" : "gm",
		"type":"BS",
		"ap":	80,
		"at" : 30,
		"pa" : 30,
		"ev" : 30,	
	]),
	"kurong-changong.roar":([
		"party" : "tls",
		"type":"DS",
		"ap":	160,
		"d_at" : 50,
		"d_pa" : 50,
		"d_ev" : 50,
		"time" : 60	
	]),
	"kurong-changong.liao":([
		"party" : "tls",
		"type":"BH",
		"ap":	80,
	]),
	"kurong-changong.kurong":([
		"party" : "tls",
		"type":"BD",
		"ap":	120,
		"armor" : 30,
		"pa" : 50,
	]),	
	"yinyun-ziqi.taiji":([
		"party" : "wd",
		"type":"BX",
		"ap":	160,
		"da" : 30,
		"pa" : 50,
	]),	
	"jiuyang-shengong.jiuyang":([
		"party" : "mj",
		"type":"BX",
		"ap":	 80,
		"at" : 10,
		"da" : 10,
		"pa" : 10,
		"ev" : 10
	]),	
	"jiuyang-shengong.xu":([
		"party" : "mj",
		"type":"BX",
		"ap":	 320,
		"at" : 100,
		"mp" : 100,
		"pa" : 50,
		"ev" : 50
	]),
	"xuantian-wuji.wuji":([
		"party" : "kl",
		"type":"BP",
		"ap":	 80,
		"pa" : 60,
	]),
	"xuantian-wuji.taxue":([
		"party" : "kl",
		"type":"BD",
		"ap":	 80,
		"ev" : 60,
	]),
	"dulong-dafa.wudi":([
		"party" : "sld",
		"type":"BA",
		"ap":	 120,
		"at" : 60,
	]),
	"dulong-dafa.shexin":([
		"party" : "sld",
		"type":"DD",
		"ap":	 160,
		"at" : 120,
		"d_da" : 50,
		"cond" : "no_perform",
		"time" : 60
	]),
	"zixia-gong.zixia":([
		"party" : "hs",
		"type":"BX",
		"ap":	 40,
		"auto" : 1,
	]),
	"linji-zhuang.youming":([
		"party" : "em",
		"type":"DD",
		"ap":	 160,
		"d_da" : 50,
		"cond" : "no_perform",
		"time" : 60
	]),
	"linji-zhuang.tiandi":([
		"party" : "em",
		"type":"BH",
		"ap":	 40,
	]),
	"linji-zhuang.fengyun":([
		"party" : "em",
		"type":"BS",
		"ap":	 80,
		"super": 15,
		"kill": 10,		 
	]),
	"linji-zhuang.yinyang":([
		"party" : "em",
		"type":"BD",
		"ap":	 80,
		"da": 40,
		"mp": 50,		 
	]),
	"bihai-chaosheng.maze":([
		"party" : "thd",
		"type":"DX",
		"ap":	40,
		"d_mp": 20,
		"d_at": 20,
		"d_pa": 30,
		"d_ev": 30,
		"time": 120  		 
	]),
]);